### ISSUE TITLE
errors in axis label for plot.survData and plot.reproData [repro - survival]

### ISSUE THREAD

**Issue by philipperuiz** [pveber/morse#110]
errors when calls axis labs arguments:

```
data(cadmium1)
# survival
ds <- survData(cadmium1)
plot(ds, xlab = "dd")
 Show Traceback 
 Rerun with Debug
 Error in dataPlotFull(data, "Nsurv", xlab, ylab, style, addlegend, ...) : 
  Unknown plot style
```

```
plot(ds, xlab = "ee", concentration = 4.36)
 Error in dataPlotFixedConc(x, "Nsurv", concentration, xlab, ylab, style,  : 
  Unknown plot style
```

`plot(ds, target.time = 21, xlab = "ee")` -> OK
`plot(ds, target.time = 21, concentration = 4.36, xlab = "ee")` -> OK

# repro
`dr <- reproData(cadmium1)
plot(dr, xlab = "ee")
 Show Traceback
 Rerun with Debug
 Error in dataPlotFull(data, "Nreprocumul", xlab, ylab, style, addlegend,  : 
  Unknown plot style`

`plot(dr, target.time = 21, xlab = "ee")
 Show Traceback
 Rerun with Debug
 Error in plot.default(x$conc, x$Nreprocumul, xlab = xlab, ylab = ylab,  : 
  formal argument "xlab" matched by multiple actual arguments`

`plot(dr, concentration = 4.36, xlab = "ee")
 Show Traceback
 Rerun with Debug
 Error in dataPlotFixedConc(x, "Nreprocumul", concentration, xlab, ylab,  : 
  Unknown plot style`

`plot(dr, concentration = 4.36, target.time =21, xlab = "ee")` -> OK

I don't know where is the problem

**Comment by pveber** [comment]
This is due to the shady semantics of "...". Better get rid of them all ;)!

**Comment by pveber** [comment]
we did that, and it's indeed working great.
