### ISSUE TITLE
plot.reproFitTT has no example.

### ISSUE THREAD

**Issue by pveber** [pveber/morse#114]
Let's use the "same" than plot.survFitTT.

**Comment by philipperuiz** [comment]
In fact `plot.survFitTT` and `plot.reproFitTT` have no example.
Plot example are in `survFitTT` and `reproFitTT`. 
But `print.reproFitTT`, `print.survFitTT`, `summary.reproFiTT` and `summary.survFitTT`
have their own example.
Maybe move the plot examples in the respective `plot` section...

**Comment by pveber** [comment]
Ok then, let's just refer to the examples of `{repro,surv}FitTT` in the documentation `plot.{repro,surv}FitTT`. I let this issue open to keep track of this.

**Comment by pveber** [comment]
done somewhere :)
