### ISSUE TITLE
Vignettes are not declared as such.

### ISSUE THREAD

**Issue by pveber** [pveber/morse#118]
```
> vignette(package="morse")
no vignettes found
```

Where should we declare vignettes?

**Comment by pveber** [comment]
precision: the problem appears only under rstudio.

**Comment by virgile-baudrot** [comment]
It's when you do not build the vignette in morse. From package in CRAN, it works:

```
 install.packages("morse") # from CRAN
vignette(package = "morse")
```
you get 

> Vignettes in package ‘morse’:
> 
> modelling                                   Models (source, pdf)
> tutorial                                    Tutorial (source, html)

And also this should open vignettes in browser:
```
browseVignettes("morse")
```
