### ISSUE TITLE
overlap in x-axis labels [survival-repro]

### ISSUE THREAD

**Issue by philipperuiz** [pveber/morse#131]
After asking stackoverflow they're apparently no automatic way to remove labels on axis automatically depanding on the window size.
For te moment, the proposed solution is a fonction to exclude som labs:

`exclude_labels <- function(x, step) {x[-seq.int(1, length(x), step)] <- ""; x}`
and to use it on  with graphical function:

`x <- data.frame(x1=1:100,x2=1:100)`
`ggplot(x, aes(x1,x2))+ geom_point() +`
`scale_x_continuous(breaks = x$x1[x$x1 %% 2 == 0],`
 `labels = exclude_labels(x$x1[x$x1 %% 2 == 0], 4))`

Perhaps use this fonction with an arguments `remove.someLabels = TRUE` ?

**Comment by pveber** [comment]
Could you provide the link on stackoverflow?

**Comment by philipperuiz** [comment]
http://stackoverflow.com/questions/32519258/overlapping-axis-label-depending-on-the-window-size
