### ISSUE TITLE
Who to compile source package (tested with the last PR of course...) [06 11 2015]

### ISSUE THREAD

**Issue by philipperuiz** [pveber/morse#150]
Vignette is building correctly only with this configuration:
RStudio + devtools + ROxygen2 v5.0.1
ecxept ROxygen2 all other packages must be up to date.
1 - RStudio config:
Project Options : `Use devtools package...` must be enable
                            `Generate documentation...` must be enable
                            `ROxygen options...` all enable exept `Vignettes` and`Source and binary package build`

2 - vignettes folder must contain only 3 files:
        biblio.bib
        modelling.Snw
        tutorial.Rmd

3 - check if a folder `inst` exist and `build` were created.

4 - update Documentation (no vignette, only NAMESPACE, Rd)
            More : Document or Ctrl + Shift + D

5 - build the source file : 
          More : Build Source Package

6 - check the vignette
       Remove old morse package
       R : `remove.packages("morse", lib="~/Documents/R/R-3.2.2/library")`
       R : `install.packages("~/Documents/morse_2.1.0.tar.gz", repos = NULL, type = "source")`
       `library("morse")`
       `?morse`

**Comment by pveber** [comment]
I guess this has been fixed...
