### ISSUE TITLE
remove ID create

### ISSUE THREAD

**Issue by philipperuiz** [pveber/morse#153]
ID create unused so remove or see if it can be changed with replic_conc without time

**Comment by philipperuiz** [comment]
actual `idCreate` function :
`idCreate <- function(data) {
  str_c(data[, "replicate"],
        data[, "conc"],
        data[, "time"],
        sep = "_")
}`
why not : 
`idCreate <- function(data) {
  str_c(data[, "replicate"],
        data[, "conc"],
        sep = "_")
}`
Now the id is a real Beaker

**Comment by pveber** [comment]
In summary: creating IDs for each line of the initial data.frame is useful in `survDataCheck` but nowhere else (so far). So we should drop that column in the class `survData` (and `reprodData`). Let's leave the function be in `morse-internal` for name.
