### ISSUE TITLE
TO DO in 2.2.0

### ISSUE THREAD

**Issue by philipperuiz** [pveber/morse#181]
- [x] add function `plotDoseResponse` and remove arg `target.time` in `plot.survData` and `plot.reproData`
- [x] check log transformation in `plotDoseResponse`
- [x] add CI in `plotDoseResponse.reproData`  #185
- [x] in `survFitTT` and `reproFitTT` always plot Cred Int, remove `ci` arg
- [x] in `survFitTT` and `reproFitTT` add new argument `plot data` `TRUE` or `FALSE` 
- [x] check the CI graphical parameter of `plot.survFitTT`
- [x] change mean curve in `plot.reproFitTT` and `plot.survFitTT`
- [x] add `ribbon` or `spaghetti` choice in `plot.reproFitTT` and `plot.survFitTT`
- [ ] resolve the `grid::unit` and `grid::arrow` import
- [x] reduce size of points in `ppc`
- [x] update documentation
- [x] update vignette
- [x] check all update in a complet version v2.2.0Complet
- [x] repare ggplot legend in `plot.reproFitTT` v2.2.0Complet
- [ ] check the gammapoisson spaghetti calcul v2.2.0Complet

**Comment by pveber** [comment]
most of it done, closing.
