### ISSUE TITLE
TO DO in 2.3.0 TKTD

### ISSUE THREAD

**Issue by philipperuiz** [pveber/morse#183]
- [x] `survFitTKTD` only complet model normal 001
- [x] add warnings for each parameters when CI is out of the prior
- [x] `ppc` change size point
- [x] update documentation
- [x] update vignette tutorial
- [ ] update vignette modelling
- [x] add dichromate and propiconazole as datasets and exemples for TKTD
- [x] summary table in scientific notation
- [x] ppc tutorial explain steps
- [x] log jitter by 4 and rewrite algo
- [x] add warnings in plot for bad combinaisons
- [x] script of mosaic TKTD page
- [x] rewrite the y =x line ppc
- [x] specify version of ggplot2
- [x] remove segment bonds in conf Int plot
- [ ] put warnings of *Fit functions in message + ID error table
- [x] plot.survFitTKTD 3 type of plot 'grid', 'one.plot', 'one.concentration'
- [x] plot.survFitTKTD generic data in black
- [x] plot.DoseResponse: two type of CI segment or box alpha (no jitter if box)
- [x] check if time in raw dataset can be float
- [x] write `EvalsurvTKTDPpc` with double `lapply`
- [x] all ppc take all mcmc
- [x] plot Conf Int segment all black
- [x] change color of fit and CI tktd to more uggly :(
- [x] `plot.survFitTKTD` rewrite to calulate CI from all mcmc samples and optimise time
- [x] remove observed value time 0 in `plot.survFitTKTD`

**Comment by philipperuiz** [comment]
follow order of commits from the 21 april on branch `total` to integrate all change of april 2016.

**Comment by pveber** [comment]
version 2.3.0 released, most of the list is done so closing.
