### ISSUE TITLE
Change formula (1) in vignette "modelling.pdf"

### ISSUE THREAD

**Issue by sandrinecharles** [pveber/morse#216]
Change 
\begin{equation}
  \label{eq:survivaldef}
  S_i(t) = \int_0^t - h_i(u)\mbox{d}u
\end{equation}

in
\begin{equation}
  \label{eq:survivaldef}
  {S_i}(t) = \exp \left(- \int_0^t h_i(u)\mbox{d}u \right)
\end{equation}

Explanation si available in the attached file.
[modelesurvie.pdf](https://github.com/pveber/morse/files/750492/modelesurvie.pdf)

**Comment by pveber** [comment]
Thanks!
