### ISSUE TITLE
wrong modification in 'survDataCheck'

### ISSUE THREAD

**Issue by virgile-baudrot** [pveber/morse#217]
See [comment on commit de3cf2d ](https://github.com/pveber/morse/commit/de3cf2d03c69d3b7487ecf5451fc66a590985984#diff-a31e5bf66f274ff5e98757612cf0ea59
)
The change done on  survDataCheck function is wrong. An option would be to write:
`if (!("data.frame" %in% class(data))) {`

**Comment by pveber** [comment]
fixed in c6f3691, thanks!
