### ISSUE TITLE
code duplication is evil (reloaded)

### ISSUE THREAD

**Issue by pveber** [pveber/morse#230]
@virgile-baudrot 
Not really happy with fc52925fc55361c89459c3b43cb0681231e25f7a. What's the issue with calling `survData`? In principle it should work: repro data really are a particular case of survival data with one more column.

**Comment by virgile-baudrot** [comment]
I agree, the code is crappy. However:
- Column `Nrepro` is not supposed to be in a `survData` class.
- Column `Nsurv` has no reason to be in a `reproData` class.
- `survData`does not return column  `Nindtime` anymore which is require in `reproData`.

Therefore, I suggest to consider `survData`and `reproData`has 2 distinct classes, as a first step.

**Comment by pveber** [comment]
Finally I kept `reproData` as a subclass of `survData`, and the call to `survData` from `reproData`. The only change is that `Nindtime` is not calculated by default in `survData` because it is not generalized (yet) to the variable exposure case. It is only calculated in `reproData`.
