### ISSUE TITLE
internal function `modelData()` should return variable requires for fitting and post fitting applications

### ISSUE THREAD

**Issue by virgile-baudrot** [pveber/morse#247]
The function `modelData()` should return all the information requires for fitting in JAGS (a list of priors, data and transformed data) in a consistent way to be easily used in the fitting process, and also to be use for post fitting applications (checking, plotting, prediction, ...).

**Comment by pveber** [comment]
fixed in 94283afb546c2777c72579f34bb08fca669e09fd
