### ISSUE TITLE
survDataCheck should check time is numeric

### ISSUE THREAD

**Issue by pveber** [pveber/morse#25]
data transformation for repro assumes (and checks, but way too late) that the time column is numeric. This should be done in a check function. Let's do it in survDataCheck, as this assumption will be needed in TKTD models as well.

We therefore need:
  - the check in survDataCheck
  - the corresponding unit test

**Comment by pveber** [comment]
Why only integers? Isn't this too restrictive?

**Comment by philipperuiz** [comment]
Yes only integers. Why would you want float? The column `time` contains the day of  the observation. The maximum is one observation per day. (or ask ML)

**Comment by pveber** [comment]
2015-03-30 9:33 GMT+02:00 philipperuiz <notifications@github.com>:

> Yes only integers. Why would you want float?
>
because this requirement does not help anywhere, and prevents datasets
where there are observations every 12h.


> The column time contains the day of the observation. The maximum is one
> observation per day. (or ask ML)
>
Is there any reason why it would make our life easier with this constraint?

**Comment by pveber** [comment]
So now, we test that time is numeric only (not integer).
