### ISSUE TITLE
URGENT : problème de nom de paramètre GUTS-IT

### ISSUE THREAD

**Issue by sandrinecharles** [pveber/morse#279]
@virgile-baudrot Lors que l'on demande un `summary()` après un `fit` du GUTS-IT, et qu'on met l'option `EFSA_name = TRUE`, il y a une erreur à corriger urgemment si possible. Le paramètre **b_w** devrait être **m_w**. Merci !

**Comment by virgile-baudrot** [comment]
Oui ce sera dans le 3.2.6.
Voir commit 71f04f32aca5e1e48a17e2cf84b71fccf3db4a45

**Comment by sandrinecharles** [comment]
Nickel !

**Comment by sandrinecharles** [comment]
C'est fait dans la version 3.2.7 non ? Si oui, on peut fermer cette issue.

**Comment by virgile-baudrot** [comment]
oui, c'est bon
