### ISSUE TITLE
Issue with LCx estimates

### ISSUE THREAD

**Issue by SingerAl** [pveber/morse#294]
Dear package maintainers,
please investigate an issue that recently occured with estimation of LCx in the current version 3.3.2 of morse on CRAN. Using the LCx function, the LCx estimates are sensitive to changes in the functions concentration range parameter 'conc_range'.  Further,  occasionally, the 2.5%-CI is higher than the 97.5%-CI. In the example calculation with the largest conc_range (conc_range = c(0, 2000)) the median estimate was outside the CI-range. See the attached example output. 
[LCx_Issue_example.pdf](https://github.com/pveber/morse/files/11515002/LCx_Issue_example.pdf)
With best regards,
Alex

**Comment by virgile-baudrot** [comment]
issue already in the official repo: see https://gitlab.com/qonfluens/model/morse/-/issues/1
