### ISSUE TITLE
Implementation of plot.survData for fixed concentration and target.time

### ISSUE THREAD

**Issue by pveber** [pveber/morse#30]
That is, write `survDataPlotReplicate` as (briefly) described in the doc.

**Comment by pveber** [comment]
This was done except the representation of the data in the control. @philipperuiz Could you add it? Please look at details in the doc.

**Comment by philipperuiz** [comment]
If concentration and target time are fixed by arguments, the representation of the data in the control are obtained by fixing the conentration at 0. I don't understand.

**Comment by pveber** [comment]
I'd like a plot to compare the observed values at a particular concentration/time with the control (concentration = 0) at the same time. You could use a "punch card"-like representation, like the one you used for plot.survData at fixed target time.

**Comment by pveber** [comment]
BTW, this is also needed for plot.reproData :)

**Comment by philipperuiz** [comment]
Is it to say two plots when concentration and time are fixed: the first one these is actualy ploted and the second the control? side by side ?

**Comment by pveber** [comment]
What we got now is fine, closing.
