### ISSUE TITLE
Reorganize unit tests.

### ISSUE THREAD

**Issue by pveber** [pveber/morse#32]
Currently in function `testthat/test-surv.R`, first we define the datasets, then perform the tests. It would be much more readable to group the definition of a dataset and the tests that are performed on it.

**Comment by philipperuiz** [comment]
the functions `test_that` of the package `testthat` are organise to  regroup multiple tests on a same test name in a same function. For now I prefer this organisation, one function regrouping the tests for a specific class or package function.

**Comment by pveber** [comment]
yes but inside your function dedicated to the test of survData, you should
group a dataset definition and the corresponding tests, so that the reader
(me) doesn't have to jump from one part of the file to the other to
understand what is written.

2015-03-25 10:07 GMT+01:00 philipperuiz <notifications@github.com>:

**Comment by pveber** [comment]
Was done too.
