### ISSUE TITLE
function plot.survDat loose of one previous plot

### ISSUE THREAD

**Issue by philipperuiz** [pveber/morse#59]
In the mosaic interface the first plot of repro/ suvival was the Number of survival / concentrations with the size of points depanding on the number of overplotted replicate. Why this plot does not exist in the new version? The most close representation is `survDataPlotTargetTime` but without the variation of size.

**Comment by pveber** [comment]
I merged your patch in #60, thanks! Note that originally we used a sunflower plot which is an interesting option too. The main weakness of your approach is that the legend will be crazy if there are more than 5 replicates. But let's leave this for later.
